services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - /opt/docker/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8085:5005
    environment:
      - PASSWORD=${PASSWORD}  # Esta será tu contraseña para editar el panel
    restart: unless-stopped
