services:
  db:
    image: mariadb:10.6
    restart: always
    # Ponlo aquí en la base de datos
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/docker/nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    # Y ponlo aquí también en la aplicación
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8082:80
    depends_on:
      - db
    volumes:
      - /opt/docker/nextcloud/data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=100.114.181.4 ubuntu-server-1.tail229932.ts.net
      - MAINTENANCE_WINDOW_START=1
