services:
  beszel:
    image: 'henrygd/beszel:latest'
    container_name: 'beszel-hub'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      # Los datos se guardar√°n en la carpeta que acabamos de crear
      - ./beszel_data:/beszel_data

  beszel-agent:
    image: 'henrygd/beszel-agent:latest'
    container_name: 'beszel-agent'
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 45876
      # La clave la pondremos en el siguiente paso
      KEY: ${BESZEL_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

